apiVersion: v1
kind: Service
metadata:
  name: {{ include "crx-client.fullname" . }}
  labels:
    {{- include "crx-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target }}
      protocol: TCP
      name: http
  selector:
    {{- include "crx-client.selectorLabels" . | nindent 4 }}
