apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets-provider  # You can customize this name based on your release name
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secrets.objectName }}
        objectType: {{ .Values.secrets.objectType }}
